# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('authtoken.token',),
        ),
    ]
